module.exports = {
  trailingComma: 'all',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  printWidth: 150,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'avoid',
  vueIndentScriptAndStyle: false,
  jsxSingleQuote: true,
  quoteProps: 'preserve',
  proseWrap: 'always',
  htmlWhitespaceSensitivity: 'strict',
};
